global:
  scrape_interval: 5s # Her 5 saniyede bir verileri çek

scrape_configs:
  - job_name: 'trendyol-api'
    static_configs:
      # Kendi API portunuzu buraya yazın (örnekte 5119). 
      # host.docker.internal, Docker'ın sizin Windows makinenize ulaşmasını sağlar.
      - targets: ['host.docker.internal:5119']